### ISSUE TITLE
Investigar PDF

### ISSUE THREAD

**Issue by PabloP95** [PabloP95/PinfBET#1]

**Comment by sheratanAlde** [comment]
He encontrado contenido interesante, en https://parzibyte.me/blog/2019/06/16/extraer-texto-imagenes-pdf-php/ y  https://github.com/parzibyte/extraer-texto-imagenes-pdf-php dentro de lo obsoleto que puede estar, es bastante actualizado

**Comment by sheratanAlde** [comment]
Finalmente esta tarea tampoco me estoy encargando yo
