### ISSUE TITLE
Pensar en el nombre de la aplicación y el nombre de las monedas

### ISSUE THREAD

**Issue by PabloP95** [PabloP95/PinfBET#10]

**Comment by sheratanAlde** [comment]
Para la moneda se me ocurre utilizar en el nombre de **CreditCoin**, jugando con la palabra crédito de las asignaturas y coin por todas las monedas virtuales que lo usan.

**Comment by sheratanAlde** [comment]
Respecto al nombre de la aplicación no se me ocurre nada con gancho comercial, por lo que os pongo las ideas que se me han ocurrido:
Apuestas o apruebas
House of Honnor -> lema: lugar donde apostar y aprobar en la ESI
Apuestas en cafetería
Apuesta o estudia
Betstudy

**Comment by sheratanAlde** [comment]
Finalmente PINFBet y Creditcoin
