### ISSUE TITLE
Investigar el tema de sociabilización

### ISSUE THREAD

**Issue by PabloP95** [PabloP95/PinfBET#7]

**Comment by sheratanAlde** [comment]
Yo la sociabilización no iría mas haya que el ser "amigos" y mandar mensajes como si fueran correos, meternos hacer salas y otras historias lo veo un poco tontería

**Comment by sheratanAlde** [comment]
Finalmente se decide por "amistades y mensajes"

**Comment by sheratanAlde** [comment]
Hay que aclarar como vamos hacer el sistema de mensajes, si tipo correos o mensajes de messenger(de ello depende poder continuar editando dicho apartado)
